# Generated by Django 4.0.4 on 2022-04-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TypeOfRoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=6, verbose_name='Room number')),
                ('floor_number', models.CharField(max_length=12, verbose_name='Floor number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_of_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TypeOfRoom.typeofroom', verbose_name='Type Of Room')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
