# Generated by Django 4.0.4 on 2022-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=6, unique=True, verbose_name='Room number'),
        ),
    ]
