# Generated by Django 4.0.4 on 2022-04-28 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TypeOfRoom', '0001_initial'),
        ('Room', '0002_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type_of_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_of_room', to='TypeOfRoom.typeofroom', verbose_name='Type Of Room'),
        ),
    ]
