# Generated by Django 4.0.4 on 2022-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Category')),
                ('number_of_people', models.IntegerField(verbose_name='Number of people')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'TypeOfRoom',
                'verbose_name_plural': 'TypeOfRooms',
            },
        ),
    ]
