# Generated by Django 4.0.4 on 2022-04-27 18:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TypeOfRoom', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='Entry date')),
                ('entry_date', models.DateField(verbose_name='Entry date')),
                ('deperture_date', models.DateField(verbose_name='Entry date')),
                ('guest_number', models.IntegerField(verbose_name='Guest number')),
                ('name_of_person', models.CharField(max_length=50, verbose_name='Name of Person')),
                ('email_of_person', models.EmailField(max_length=250, verbose_name='Email of Person')),
                ('phone_number_person', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Toal price')),
                ('localizador', models.CharField(max_length=8, verbose_name='Localizador')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.room', verbose_name='Room')),
                ('type_of_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TypeOfRoom.typeofroom', verbose_name='Type of room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
