# Generated by Django 4.0.4 on 2022-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='type_of_room',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deperture_date',
            field=models.DateField(verbose_name='Deperture date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Reservation date'),
        ),
    ]
