# Generated by Django 4.0.4 on 2022-04-28 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0004_remove_reservation_type_of_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=5, verbose_name='Confirmation_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Confirmation code time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
    ]
