# Generated by Django 4.0.4 on 2022-04-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_reservation_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_code_time',
            field=models.DateTimeField(verbose_name='Confirmation code time'),
        ),
    ]
