# Generated by Django 4.0.4 on 2022-04-28 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_room_number'),
        ('Reservation', '0006_alter_reservation_confirmation_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room', to='Room.room', verbose_name='Room'),
        ),
    ]
